Richie transaction modal visual progress indicator
nickick/drift-vault pull request #2
Opened 2023-08-30 20:05 UTC by richardjhong

- resetting checkedTokenIds to empty array when successful on vaulting to prevent potential faulty vaultBatch of NFTs that are already vaulted
- removing code that is no longer in use
- switching from intel based MBP to apple silicon MBP which changes yarn and package-lock

2023-08-31 21:55 UTC, nickick requested changes

2023-08-31 21:55 UTC, nickick commented on package-lock.json
Let's remove this file. Since we're using yarn, stick to using the yarn.lock over the package.lock

2023-08-31 21:59 UTC, richardjhong commented on package-lock.json
done, removed package-lock

2023-10-09 17:52 UTC, nickick approved these changes
LGTM, thanks

2023-10-09 17:52 UTC, merged